### ISSUE TITLE
Update to latest version?

### ISSUE THREAD

**Issue by rain-1** [brkyzdmr/TemplateMatcher#1]
This looks amazing, but I could not get it to work on the latest version of opencv and I couldn't install older versions.

Is it possible to get it running on new opencv?

I tried changing cv2.xfeatures2d.SIFT_create() to cv2.SIFT_create() as a start.

and then I have an issue with dst = cv2.perspectiveTransform(pts, M)   that I couldn't figure out. I guess the functions changed over time.

**Comment by brkyzdmr** [comment]
The project has been upgraded to the latest OpenCV version 4.5.5.64
