### ISSUE TITLE
errors in function

### ISSUE THREAD

**Issue by theBrom8** [brkyzdmr/TemplateMatcher#4]
Hello, 

and thank your for your template!

I was trying to implement your "get_matched_coordinates" into my script to locate icons on a picture.

First it had problems, when my picture was in color!?  but you where useing colored pictures yourself..

and then the thing i couldnt solve on my own happend:
"OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matmul.dispatch.cpp:550: error: (-215:Assertion failed) scn + 1 == m.cols in function 'cv::perspectiveTransform'"

i would be suuper happy if you could give me some support or point me in a direction, or if needed, update your script!

Greeting Johnny

**Comment by brkyzdmr** [comment]
I apologize for my delayed response. In the main function, I am importing images in grayscale format. As you can see from the resulting images, they are displayed in grayscale. Although the original images are in color, they are being imported in grayscale format during the importing phase.

```python
# read images
temp_img_gray = cv2.imread(args.template, 0) # 0 means grayscale
map_img_gray = cv2.imread(args.map, 0) # 0 means grayscale
```
